### ISSUE TITLE
BTT mini 12864 display not working with BTT Skr mini e3 v2 board

### ISSUE THREAD

**Issue by ramsoni08** [gsl12/Tiny-M#19] opened 2021-09-24 15:18 UTC
how to connect BTT mini 12864 display with BTT Skr e3 mini v2 board ?? in klipper firmware??

**Comment by properlypurple** [comment] 2021-12-01 15:08
@ramsoni08 If you still need this to work, you should check the pinout here
https://github.com/bigtreetech/BGTHREETECH-MINI-12864-V1.0/blob/main/Hardware/BIGTREETECH%20MINI12864%20Interface.pdf

CLosing this as this is not a bug in the printer itself

**Closed by properlypurple** 2021-12-01 15:08 UTC

**Comment by jtrmal** [comment] 2021-12-01 15:11
also this might be a solution
https://deepfriedhero.in/products/skr-mini-screen-adaptor-by-timmit99
